---
- name: defining target group
  hosts: nikhil-roche
  vars:
   x: httpd
   z: git
  #become true means sudo access
  become: true
  tasks:
  - name:  testing ping module 
    ping:

  - name: running sample commands 
    command: date

  - name: Installing {{x}} and {{z}} software in target amazon linux machine 
    yum: 
      name: 
      - "{{x}}"
      - "{{z}}"
      state: present 

  - name: copy code to httpd app server loc
    copy:
      src: myapps/index.html
      dest: /var/www/html/

  - name: staring {{x}} service
    service:
      name: "{{x}}"
      state: started
      enable: yes
        
   