name: ashuothshh job 
# trigger point 
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "terraform.tfstate"
 
# creating jobs 
jobs:
  infra-provision-job:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    # calling first github action to clone my dryrun-aws data to runner machine 
    - name: taking code from my repo 
      uses: actions/checkout@v5
      with:
        ref: main 
# terrafor installing 
    - name: installing terraform 
      uses: hashicorp/setup-terraform@v3
# running some commands 
    - name: my first step to test github action 
      run: |
        echo "Hello world"
        git version 
        whoami
        ls -a 
        terraform version
    # configure aws secret keys 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: ap-southeast-2

    - name: verify aws connection 
      run: | 
        echo "checking with command"
        aws s3 ls 
    - name: deploy terraform resources 
      run: | 
        echo "implementing terraform deals"
        terraform init 
        terraform plan 
        sleep 2
        terraform apply --auto-approve
        ls modules/ec2
    - name: upload ansible inventory to github artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nikhil-github-artifact
        path: |
          modules/ec2/myip.txt
          modules/ec2/nikhilKey.pem


  infra-configure-job:
    needs: infra-provision-job
    runs-on: ubuntu-latest
    steps:
    - name: checking out code 
      uses: actions/checkout@v5
      with:
        ref: main 
        sparse-checkout: |
          my-ansible
    - name: verify checkout 
      run: | 
        ls -R 
#downloading artifact
    - name: downloading ansible-inventory as artifact
      uses: actions/download-artifact@v4
      with:
        name: nikhil-github-artifact
#listing artifact
    - name: display structure of download file
      run: ls -R
  
    # isntalling  
    - name: installing ansible 
      run: | 
        echo "setup of ansible in ubunt"
        sudo apt update
        sudo apt install ansible2 -y
        ancible --version
  